// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kphbgjndefbpmqwdrnup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwaGJnam5kZWZicG1xd2RybnVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNjAzNzMsImV4cCI6MjA3MTkzNjM3M30.hGpCzq1-_MRqonpTlLofmAV3-4vB4qTk7r4sHnlRkAQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});